### ISSUE TITLE
Getting fine-tuned embeddings from Roberta trained on binary classification

### ISSUE THREAD

**Issue by klimentij** [ThilinaRajapakse/simpletransformers#104]
Hi and thank you so much for this awesome library. Although it's based on Transformers, it delivers a huge value: business often needs some quick and dirty experiment results asap, and your library help me a lot with it. 

I trained a Roberta model on a binary classification task. I guess this model fine-tuned embeddings on my domain during training. How can I use this model to get the actual embedding vector for a given input text to use in downstream tasks (e.g. textual similarity)?

**Comment by AliOsm** [comment]
Hello @klimentij 

For this purpose, you can use this package: https://github.com/AliOsm/simplerepresentations. SimpleRepresentations allows you to extract the feature vectors from any Transformer-based language models. In your case, instead of giving the library the model name that you want to use, give it the path to your fine-tuned model.

Tell us what happens with you!

**Comment by klimentij** [comment]
I'll try it out, thank you!
