### ISSUE TITLE
Can I get sentence encoding?

### ISSUE THREAD

**Issue by orko19** [ThilinaRajapakse/simpletransformers#1113]
Is it possible to get an encoding (1X768 vector) with this package, where the encoding is the mean of the last hidden layer, or the [CLS] token of the last hidden layer?
I saw the class  `RepresentationModel` , is this what it does? Couldn't understand from the example

**Comment by aronszanto** [comment]
`RepresentationModel.encode_sentences` is exactly what you're looking for. The example [here](https://simpletransformers.ai/docs/text-rep-examples/#minimal-example-for-generating-sentence-embeddings) is quite useful.

**Comment by orko19** [comment]
@aronszanto Thanks! what is the concat strategy from here: https://simpletransformers.ai/docs/text-rep-model/https://simpletransformers.ai/docs/text-rep-model/ ?
Is it possible to just take the [CLS] token as the encoding? I saw it's pretty common

**Comment by orko19** [comment]
@aronszanto Any idea if it's possible to use to [CLS] token?

**Comment by aronszanto** [comment]
Hi @orko19- I'm not a maintainer or contributor to `simpletransformers`. I do suggest reading some of the documentation in the codebase, which provides helpful answers to your questions:

1. [Here](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/language_representation/representation_model.py#L153) is a note about using the `<CLS>` token ("combine_strategy: strategy for combining word vectors, supported values: None, "mean", "concat", or an int value to select a specific embedding (e.g. 0 for [CLS] or -1 for the last one")
2. [Here](https://simpletransformers.ai/docs/usage/#loading-a-local-save) is a note about using your own saved model.

In general, it's good etiquette and respectful to the (volunteer) maintainer(s) to check the docs before posting an issue so that they can spend more time developing superb packages like this one :)
