### ISSUE TITLE
BART-Large loading problem

### ISSUE THREAD

**Issue by prajwal20** [ThilinaRajapakse/simpletransformers#1226]
I am using the latest version of simpletransformers, and using the BART Seq2Seq model to train on custom data.

I however have no internet connection on the server so I downloaded the BART-Large model locally and uploaded it to my server,

And I gave the path to the uploaded file when calling the model.

But I get the below error.

Attaching screenshot of code and error

Also When loaded in this way there is no problem at all, but simpletransforner loading is not working correctly,
from transformers import BartTokenizer, BartModel
model = BartModel.from_pretrained('bart-large')

I need some help in resolving this, thanks for the help in advance.

![image](https://user-images.githubusercontent.com/27149172/128347451-9bf9a0b8-6cb3-489c-a9be-fe9d49786ec8.png)

![image](https://user-images.githubusercontent.com/27149172/128347395-a34386a7-79d8-4076-bff4-3e5900a1cd1d.png)

**Comment by Zhylkaaa** [comment]
hey, it seems that the problem is with file permissions for tokenizer.
Can you run `BartTokenizer.from_pretrained('bart-large')` and `BartTokenizerFast.from_pretrained('bart-large')`?
Also can you run `!ls -la bart-large` and show as the output? Maybe you just need to run `chmod 644 <filename>` on some files in that directory. Maybe this is uploading problem

**Comment by prajwal20** [comment]
Thanks for the help

Attaching screenshot of **ls -la bart-large**
![image](https://user-images.githubusercontent.com/27149172/128655529-8f3349b1-1158-4273-a23d-051f88e71ac3.png)


Also attaching screenshot of BartTokenizer.from_pretrained('bart-large') and BartTokenizerFast.from_pretrained('bart-large')

![image](https://user-images.githubusercontent.com/27149172/128655581-d57df0a7-2ffa-4094-b59e-1a64b55a0c3a.png)

![image](https://user-images.githubusercontent.com/27149172/128655595-4be6dd30-19a9-4877-b029-07134d5ab519.png)

With BartTokenizerFast.from_pretrained('bart-large') I get the same error as earlier

**Comment by Zhylkaaa** [comment]
hmmm, I unfortunately don't have time to dig into it, but there are some issues with bart tokenizer on internet (probably it's saving or versions incompatibility). The quick and ***probably*** working solution is to just change BartTokenizerFast import to BartTokenizer  and also hear https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/seq2seq/seq2seq_model.py#L101 in sources. probably because there can be slight changes in tokenization between two Tokenizers (they usually not perfectly compatible, but if the original checkpoint was trained with BartTokenizer I don't think it will break anything).

Have a good day 🤗

**Comment by prajwal20** [comment]
Thanks a lot @Zhylkaaa !!

I changed it to BartTokenizer in seq2seq_model.py#L101, And is now working fine.

Also will look into some issues wrt BART tokenizer as well.

Thanks Again for the help!!
