### ISSUE TITLE
NER model's predict() function can support conll format file? 

### ISSUE THREAD

**Issue by azizcu** [ThilinaRajapakse/simpletransformers#1352]
I want to use the NER model's predict() function like the eval_model() function which support conll format file.
results, model_outputs, predictions = model.eval_model(data/conllFormatFile.txt) like this. 

Also want similar output of predict() function like this : [['B-PER', 'O', 'O', 'B-PER'], ['O', 'B-PER', 'O', 'O', 'O', 'O']] 
But predict() function gives a dictionary for each token within list.

**Comment by whr778** [comment]
There are two ways to call predict:  1) You can pass an array of strings,
or 2) you can pass an array of arrays of unigram tokens.  The second way
would only require unigram tokenization preprocessing of the input samples
if the samples are text.

CoNLL is even easier because each line in conll consists of a unigram
token, either a space or tab delimiter, and a label.Sentences or samples
are separated by an empty line \n.  Preprocessing conll into the #2 option
above is simple to implement.

Bill
