### ISSUE TITLE
Regarding Hardware resources for Bert/ULMFit and deep learning algorithms

### ISSUE THREAD

**Issue by ahujaravinder022** [ThilinaRajapakse/simpletransformers#142]
Dear 
             I am having a data set of 198350 rows. I am using Kaggle GPU and when I tried to execute Bert code on it, it took 10-12 hours and then disconnected. It happens 3-4 times(I am not able to run the code completely--during training it is taking time).

I have tried google collab also but no output.

Plz guide me which configuration of the laptop will be required for this much amount of data.

Is there is any online way of using GPU whose cost is less as compared to purchasing a laptop.

Can you please run the code on your machine, if I mail u the data set. It will be a great help to me and I will be highly obliged for the same. 

Thanks and Regards
Ravinder Ahuja

**Comment by ThilinaRajapakse** [comment]
A dataset of 198350 is of significant size and it might indeed be too large to train within the 12 hour limit on free GPUs.

You could try training it for 1 training epoch as I think that won't take 12 hours. Make sure that you are using the biggest possible batch size to ensure maximum GPU utilization.

You could also try using the free 300$ credits from Google Cloud. I'm not sure how far the 300$ will get you, but I guess it's worth a shot.

In general, I would recommend at least a GTX 1060. I think the GTX 1660 offers better performance at a similar price point, so that might be a better choice.

From what I can tell, investing in a GPU of your own is more cost-effective in the long run than using cloud GPUs, assuming you plan on continuing to work in AI/Deep Learning.

Unfortunately, I am unable to run your experiment on my machine at this time.

**Comment by ahujaravinder022** [comment]
Thanks a lot...
