### ISSUE TITLE
from simpletransformers.classification import ClassificationModel has issues with latest version of transformers

### ISSUE THREAD

**Issue by PaulTran47** [ThilinaRajapakse/simpletransformers#1572]
Under the latest version of Google Colab, I ran into an issue when starting up my usual script with simpletransformers:

```
from simpletransformers.classification import ClassificationModel, ClassificationArgs
```

The following error occurs:

```
/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/__init__.py in <module>
      1 from simpletransformers.classification.classification_model import ClassificationModel
----> 2 from simpletransformers.classification.multi_label_classification_model import (
      3     MultiLabelClassificationModel,
      4 )
      5 from simpletransformers.classification.multi_modal_classification_model import (

/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/multi_label_classification_model.py in <module>
     49 from simpletransformers.config.model_args import MultiLabelClassificationArgs
     50 from simpletransformers.config.utils import sweep_config_to_sweep_values
---> 51 from simpletransformers.custom_models.models import (
     52     AlbertForMultiLabelSequenceClassification,
     53     BertForMultiLabelSequenceClassification,

/usr/local/lib/python3.10/dist-packages/simpletransformers/custom_models/models.py in <module>
     35 )
     36 from transformers.models.camembert.configuration_camembert import CamembertConfig
---> 37 from transformers.models.camembert.modeling_camembert import (
     38     CAMEMBERT_PRETRAINED_MODEL_ARCHIVE_LIST,
     39 )

ImportError: cannot import name 'CAMEMBERT_PRETRAINED_MODEL_ARCHIVE_LIST' from 'transformers.models.camembert.modeling_camembert' (/usr/local/lib/python3.10/dist-packages/transformers/models/camembert/modeling_camembert.py)
```

Looking into the scripts, it looks like the variables named "..._ARCHIVE_LIST" no longer exist in configuration_camembert and/or modeling_camembert.

When downgrading from the latest version of transformers (4.41.0) to version 4.40.2, the issue no longer appears.

I apologise if what I've described is not precise enough. I'm not familiar in the specifics of the programmes in both simpletransformers and transformers.

**Comment by PaulTran47** [comment]
> Unfortunately that doesn't work for me but another (temporary) workaround is to do "Tools > Command palette > Use fallback version"

That's very strange. Just to make sure I understand, "Use fallback version" essentially forces Google Colab to run on a fallback/previous runtime version, correct? I've only heard of this command from others wanting to temporarily run Colab on Python 3.9 instead of 3.10.

Do you still run into issues with classification models when installing simpletransformers and transformers as the following:

```
!pip install transformers==4.40.2
!pip install simpletransformers
```

**Comment by jblom** [comment]
Also had this problem and fixed it by pinning the transformers version as well (snippet from my `requirements.txt`):

```
transformers==4.40.2
simpletransformers==0.64.3
```

**Comment by ThilinaRajapakse** [comment]
This should be fixed now. Classification tasks should work with the latest Transformers version.

**Comment by PaulTran47** [comment]
Just confirmed that classification tasks run without any issues on the latest version of Transformers. 

Thanks for the quick fix!

**Comment by Veronicacz** [comment]
Hi @ThilinaRajapakse,
I encountered this issue again,  [from simpletransformers.classification import ClassificationModel has issues with](https://github.com/ThilinaRajapakse/simpletransformers/issues/1572#top)
`transformers==4.49.0
simpletransformers==0.70.0`
Could you please advise on the possible solutions? Thank you!

**Comment by paultran47** [comment]
@Veronicacz If it helps, what has been working for me since closing this thread has been using the latest version of simpletransformers (0.70.1), but downgrading transformers to version 4.42.4:

```
!pip install transformers==4.42.4
!pip install simpletransformers
```

I believe the error you're experiencing is because you're still using simpletransformers version 0.70. 0.70.1 should address what you're dealing with. 

You should also downgrade to transformers version 4.42.4 because of this other issue:

https://github.com/ThilinaRajapakse/simpletransformers/issues/1582

**Comment by Veronicacz** [comment]
> [@Veronicacz](https://github.com/Veronicacz) If it helps, what has been working for me since closing this thread has been using the latest version of simpletransformers (0.70.1), but downgrading transformers to version 4.42.4:
> 
> ```
> !pip install transformers==4.42.4
> !pip install simpletransformers
> ```
> 
> I believe the error you're experiencing is because you're still using simpletransformers version 0.70. 0.70.1 should address what you're dealing with.
> 
> You should also downgrade to transformers version 4.42.4 because of this other issue:
> 
> [#1582](https://github.com/ThilinaRajapakse/simpletransformers/issues/1582)

Thanks @paultran47 for your reply! Upgrading `simpletransformers `to 0.70.1 resolves the issue I encountered! 
However we cannot downgrade to transformers versions < 4.48 due to the security vulnerability [CVE-2024-11393](https://github.com/advisories/GHSA-wrfc-pvp9-mr9g). Hopefully the other issue you pointed out would not impact us :(

**Comment by paultran47** [comment]
> > [@Veronicacz](https://github.com/Veronicacz) If it helps, what has been working for me since closing this thread has been using the latest version of simpletransformers (0.70.1), but downgrading transformers to version 4.42.4:
> > 
> > ```
> > !pip install transformers==4.42.4
> > !pip install simpletransformers
> > ```
> > 
> > I believe the error you're experiencing is because you're still using simpletransformers version 0.70. 0.70.1 should address what you're dealing with.
> > 
> > You should also downgrade to transformers version 4.42.4 because of this other issue:
> > 
> > [#1582](https://github.com/ThilinaRajapakse/simpletransformers/issues/1582)
> 
> Thanks @paultran47 for your reply! Upgrading `simpletransformers `to 0.70.1 resolves the issue I encountered! 
> However we cannot downgrade to transformers versions < 4.48 due to the security vulnerability [CVE-2024-11393](https://github.com/advisories/GHSA-wrfc-pvp9-mr9g). Hopefully the other issue you pointed out would not impact us :(

Yeah of course. Regarding the downgrade issue with transformers, that's definitely a risk to use version 4.42.4.

Unfortunately we're stuck between a rock and a hard place since simpletransformers hasn't been updated to work with the newest version of transformers yet. Might actually be worth to open up a new issue regarding this vulnerability.

At the very least, I think our risk exposure is limited since the vulnerability seems to only be exposed to the user if we interact with a malicious file. As long as we have full control over the input files we feed into the models we're using, we shouldn't be exposed.
