### ISSUE TITLE
Model predict result differs every time model is loaded

### ISSUE THREAD

**Issue by jotapem** [ThilinaRajapakse/simpletransformers#214]
**Behavior description**
I have a simple script that loads a pretrained model and outputs its prediction result w.r.t to a constant string. After the model is loaded I obtain the same result if I predict on the same string multiple times. However, if I run the script again, the output is not the same. I am new to NLP and LSTMs, so I am not even sure this is a bug. To my understanding, a given model should output the same prediction given the same input. Is it true for NLP/NER? If so, how do I change my code to obtain such behavior? Otherwise, I appreciate if someone more experienced than me on NLP and NER could point me to references that discuss how I may apply this non-deterministic behavior to real-world tasks.

Thank you.

**Code**
```
from simpletransformers.ner.ner_model import NERModel

use_cuda = True
# Create a NERModel
model_default = NERModel('bert', 'bert-base-cased', use_cuda=use_cuda, args={"reprocess_input_data": True, 'use_cached_eval_features' : False})
model_default.model.eval()

sentence = "EU rejects German call to boycott British lamb."

print("Default 1 ", model_default.predict([".", sentence]))
print("Default 2 ", model_default.predict([".", sentence]))
```
**System configuration**
Ubuntu 18.04
Python 3.8.1
PyTorch 1.4.0
Cuda 10.0

**Comment by ThilinaRajapakse** [comment]
The reason for this behaviour is that the pre-trained BERT model (bert-base-cased in this case) only contains pre-trained weights for the Transformer itself. To use this model for some task, we add a linear layer on top of the Transformer that takes the _output_ from the _Transformer_ as its _input_ and gives out an output that can be used for the task at hand.

When you create a task-specific model such as NERModel, this linear layer is initialized randomly as it is not a part of the pre-training. Since it is initialized randomly, you will get different outputs for the same input when you create the model multiple times.

However, once you fine-tune the model on your task, the weights of the linear layer too will get updated and saved. When you save and load a fine-tuned model, you will get the same output for the same input no matter how many times you load the model.

**Comment by jotapem** [comment]
Thank you for your answer! I was able to achieve the behavior I expected by storing model weights right after `NERModel` is instantiated on the first run and explicitly reloading them on the next ones.
