### ISSUE TITLE
Question: Does NERModel support sliding_window?

### ISSUE THREAD

**Issue by esdu** [ThilinaRajapakse/simpletransformers#227]
Hello, I was wondering how does the NERModel deal with long documents. Specifically can we provide the `sliding_window` argument to deal with this?

Alternatively, are there any best practices to handle long documents that have not been implemented into this library?

Thanks!

**Comment by ThilinaRajapakse** [comment]
No, it's only implemented for classification tasks at the moment. However, you should be able to manually split the dataset to keep all text under the sequence length limit. I would recommend making sure that the splits are made at the end of sentences or perhaps even the ends of paragraphs only. This is because NER is more sensitive to where you split the windows compared to classification.

Not that I am aware of! I'm happy to include any if they do exist. :smile:

**Comment by esdu** [comment]
Okay that makes sense. 2 followup questions:

1. Is the max sequence length the number of words (ie the number of rows in the input dataframe per sentence_id, in the case of NER)? Or is it the number of tokens from BERT's tokenizer?
2. Is there any documentation on how NER is implemented? Any insights here is very useful :)

**Comment by ThilinaRajapakse** [comment]
1. The number of tokens after tokenizing with BERT's tokenizer. 3 or 4 (depending on the model) tokens are reserved for special tokens like _end of setence_ as well.
2. There's no additional documentation other than what is in the readme and in the source code comments. The source code shouldn't be too difficult to follow and I'm happy to answer any questions you have regarding it. A lot of it is heavily based on the Transformers package so you might also find additional information there.

**Comment by esdu** [comment]
Ok great, I can look into the code more.

One last question - I would like to know ahead of time how many tokens a sentence would be turned into (so I know where to split it) Is there a function in the codebase to do that?

**Comment by esdu** [comment]
Looks like `model.tokenizer.tokenize('myword')` + [special_token_count](https://github.com/ThilinaRajapakse/simpletransformers/blob/master/simpletransformers/ner/ner_utils.py#L116) will do the job.

Thank you again!

**Comment by DebanjanaKar** [comment]
> No, it's only implemented for classification tasks at the moment. However, you should be able to manually split the dataset to keep all text under the sequence length limit. I would recommend making sure that the splits are made at the end of sentences or perhaps even the ends of paragraphs only. This is because NER is more sensitive to where you split the windows compared to classification.
> 
> Not that I am aware of! I'm happy to include any if they do exist. 😄

Why do you say "NER is more sensitive to where you split the windows compared to classification."?

**Comment by ThilinaRajapakse** [comment]
Because NER is a token level task, I assumed that it would be more sensitive. If a word gets split in the middle, then it certainly changes the assigned NER tag (it would also create two tags for the two pieces of the word). If a sentence gets split, that might potentially change the tags for each word in the sentence as the meaning of the sentence is likely to change (or stop being meaningful altogether).

For classification, this should be less of an issue as classification generally depends on the sequence as a whole.

**Comment by DebanjanaKar** [comment]
That makes sense..thanks a lot 😄
