### ISSUE TITLE
Predictions for the model

### ISSUE THREAD

**Issue by wadhwasahil** [ThilinaRajapakse/simpletransformers#230]
Hello,

I was exploring the `predict` method for the model. So the `predict`  gives two values, first is the array of 1s and 0s and second is the values of floats.

I have a few questions.
1.  How do you calculate the 0s and 1s array, is it based on some probability or what?
2. What are the values in the float array? Are they activation values? Also, how can I convert them to probabilities? Doing a softmax over them won't make sense because the model is trained in a 1vsall way.

Thanks

**Comment by kinoute** [comment]
Hi,

To convert the `raw_outputs`, you can use softmax from the scipy library:

```py
from scipy.special import softmax

probabilities = softmax(raw_outputs, axis=1)
```

It will convert the float numbers to fix predictions like [0.12374 0.87612]

**Comment by wadhwasahil** [comment]
I want to understand how do you come up with the predictions of 1s and 0s in first place? How do you decide which label is present in the text?

**Comment by ThilinaRajapakse** [comment]
By applying softmax over the predictions and selecting the label with a higher probability.

**Comment by wadhwasahil** [comment]
What if there are multiple labels in the text? How do you select top k labels if there are any?

**Comment by ThilinaRajapakse** [comment]
With multilabel classification, any model outputs above `args["threshold"]` gets rounded off to 1 and anything below gets rounded off to 0. The default threshold is 0.

If you want top k labels, shouldn't you be using multiclass classification instead? To use image classification as an example (as it is easier), consider an image of an animal.
Multiclass classification will give you the probabilities for it being a certain kind of animal (90% dog, 7% wolf, 2% cat, 1% others). Top k with k=3 will give you dog, wolf, and cat.
Multilabel classification is not mutually exclusive. If your image has a dog _and_ a cat, it will say;
```
dog: 1
cat: 1
wolf: 0
others: 0
```
I'm not sure what top k will mean in this instance. Since the labels are not related to each other, I'm not sure how they can be compared.

**Comment by wadhwasahil** [comment]
So, basically, after you have softmax the transformations in the output layer, you convert them based on the threshold which is basically 0.5, right? Actually, I have to implement multi-label classification which assumes each label is independent of each other. I assume you must have done 1vsAll based approach to handle multilabel classification problem.

Thanks

**Comment by ThilinaRajapakse** [comment]
Yes.

You'd be right to assume that I know what the 1 vs all approach is. What I pointed out was that if the labels are independent of each other, you cannot select a top k based on the scores given by the model for each label as they are _independent of each other_.
