### ISSUE TITLE
Confusion matrix for multilabel model

### ISSUE THREAD

**Issue by ns-hxue** [ThilinaRajapakse/simpletransformers#256]
I was trying to get the confusion matrix for a trained multilabel mode.

sklearn does support multilabel confusion matrix  with sklearn.metrics.multilabel_confusion_matrix

However, when I passed this to the eval() method, it gives me an error 

ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets

Any idea why?

**Comment by ThilinaRajapakse** [comment]
I think the values that get passed to the sklearn method are not rounded off to 1/0 (i.e. continuous). Can you check this?
If so, you'll need to threshold the values and round off before sending to the sklearn method.

**Comment by ns-hxue** [comment]
Okay, thanks for the clarification. One more question, the predictions of
my model are always the same and the probs are never changed. Do you think
I did something wrong while training?

**Comment by ThilinaRajapakse** [comment]
Check whether `reprocess_input_data` is set to True (it should be). There could be some other issues as well, which you can find by poking around earlier issues related to this.

It's unlikely that this is due to your training. It's probably some arg being set incorrectly which is causing cached features to be used.

**Comment by Sphinxs** [comment]
Same problem here and `reprocess_input_data` is set to `True`.
