### ISSUE TITLE
Docs on picking a model type

### ISSUE THREAD

**Issue by JacksonKearl** [ThilinaRajapakse/simpletransformers#352]
In docs, there's a list of supported model types, which is all well and good, but it might be nice to have a couple words for each about when/why one would use that model. Just a thought, as I don't really know where to start and I'm looking to this project for more of a "plug and play" approach than a "read a bunch of papers" approach. 🙂

**Comment by ThilinaRajapakse** [comment]
"Read a bunch of papers" approach does sound mildly terrifying! I'll what I can do. The issue is that there is no standard when/why to use a particular model. But, I guess even information like "this is big" and "this is kinda slower" could possibly be helpful.

Please do share any other suggestions you have regarding the docs. I'm trying to get some feedback in #342 .
