### ISSUE TITLE
xlm-roberta-bert is taking lot of time and multiprocessing is disabled as well

### ISSUE THREAD

**Issue by suryapa1** [ThilinaRajapakse/simpletransformers#398]
**Describe the bug**

Even for 100 documents training is taking more than expected time like 20+hrs for xlm-roberta-large as model_type, Is there any workaround for this to work

**Comment by suryapa1** [comment]
Why this functionality is disabled:
UserWarning: use_multiprocessing automatically disabled as xlmroberta fails when using multiprocessing for feature conversion.
  f"use_multiprocessing automatically disabled as {model_type}"

**Comment by ThilinaRajapakse** [comment]
The warning states why it's disabled. Because using multiprocessing generates an error with xlmroberta for some reason.

The training time depends on a lot of factors like the size of the model, the type of the model, the GPU you are using, etc. So it's impossible for me to say why it's taking 20+ hours or even whether that's unexpected.

**Comment by suryapa1** [comment]
Model am using is xlm-Roberta-base with 17000 documents for now with 17 labels , gpu is p2x,16gb gpu memory , any suggestion for me on mode type of xlm-bert as model has to support english and German language

**Comment by suryapa1** [comment]
Does xlm-Roberta supports TPU, If so how to enable tpu on the same

**Comment by ThilinaRajapakse** [comment]
Do you have very long documents? 17000 sample dataset shouldn't take that long to train.

Simple Transformers doesn't have native TPU support yet.
