### ISSUE TITLE
ImportError: cannot import name 'AddedToken' from 'tokenizers' 

### ISSUE THREAD

**Issue by debadityamandal** [ThilinaRajapakse/simpletransformers#412]
I installed simpletransformer by following command
pip install simpletransformers
After installing this library, I tried to import QuestionAnsweringModel. At that time I got this ImportError.

**Comment by TechyNilesh** [comment]
Okay, turns out the transformers installer pulls an older version (0.0.11). So...

```
pip uninstall tokenizers
pip install tokenizers==0.4.2
```

...fixes it. It does issues a warning: ERROR: transformers 2.4.1 has requirement tokenizers==0.0.11, but you'll have tokenizers 0.4.2 which is incompatible., but this can safely be ignored (this answer came from @julien-c at huggingface/tokenizers)

**Comment by debadityamandal** [comment]
It worked for me.Thank you @TechyNilesh

**Comment by wiseyoungbuck** [comment]
I was getting the error:
```
TypeError: cannot pickle 'AddedToken' object
with 
```
```
tokenizers == 0.7.0
transformers==3.0.2
simpletransformers==0.41.2
```

I fixed it with
``
pip uninstall tokenizers
pip install tokenizers
``

But my conda environment gave me a warning of a tokenizer conflict between transformers and simpletransformers.

**Comment by ThilinaRajapakse** [comment]
You should be able to use the latest versions of everything without any issues. That warning seems to be a false alarm for now.

Easiest way to go is to just do `pip install simpletransformers` and it should grab the correct transformers and tokenizers versions.
