### ISSUE TITLE
error when running the code with multilingual BERT

### ISSUE THREAD

**Issue by azamatolegen** [ThilinaRajapakse/simpletransformers#47]
is mBERT supported? 
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    model = ClassificationModel('bert', 'model/', args=({'fp16': False}))
  File "/home/data/anaconda3/envs/pytorch/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 69, in __init__
    self.model = model_class.from_pretrained(model_name, num_labels=num_labels)
  File "/home/data/anaconda3/envs/pytorch/lib/python3.6/site-packages/transformers/modeling_utils.py", line 345, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/home/data/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/data/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
MemoryError

I just downloaded mBERT model (uncased_L-12_H-768_A-12: bert_config.json; bert_model.ckpt.data-00000-of-00001; bert_model.ckpt.index; bert_model.ckpt.meta; vocab.txt) and putted them in model/ directory. Data set and other part of code are same. How to deal with that error? Thanks a lot!

**Comment by ThilinaRajapakse** [comment]
Any bert model should be working.

You seem to be getting a `MemoryError`. Are you running out of RAM?

**Comment by azamatolegen** [comment]
Hi Thilina. I used XLM model with smaller subset (100K train, 10K test) and it worked just fine. Now I am trying to use mBERT, but it doesn't work with even smaller dataset (20K train, 2K test). How do I control running out of RAM error? Is it related to the size of the model parameters or to the amount of data I am feeding to the model?
Could you please show me some light on this?
I am learning a lot from your articles! I greatly appreciate the time and effort you put into this.

**Comment by ThilinaRajapakse** [comment]
If you are running the model on a GPU, the size of the model itself shouldn't cause a RAM related memory error. Rather, it would throw a cuda memory error as you would be running out of memory on the GPU itself.
The size of the dataset itself is the biggest factor that affects the amount of RAM used. Converting the dataset into input features is probably the most memory intensive stage of the entire process and this is the part that you should pay the most attention to. Using multiprocessing considerably speeds up the conversion but it comes at the cost of memory. Try lowering the `process_count` argument or turning off multiprocessing altogether by setting `use_multiprocessing = False`. I _think_ the model type might affect memory usage here as the conversion process might be different for different models.

If you are running on a CPU, everything from the size of the dataset and the size of the model is going to affect RAM usage, because everything is living on the RAM itself. Even increasing the batch size will increase the amount of RAM used.

I am delighted to hear that my articles have been helpful!

**Comment by bhardwaj1230** [comment]
Help with loading mbert model :
Not sure how to load mBert model for classification task, I have tried but getting errors like "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte"

There must be some silly error I must have made. Any suggestion will help. Thank you.

Code:
train_args={
    'num_train_epochs': 1,
    'sliding_window': True,
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
    'evaluate_during_training': True,
    'batch_size': 8,
    'logging_steps': 5,
    'stride': 0.8,
    'max_seq_length': 128, # 128/256/512
    'use_early_stopping': True,
    'early_stopping_patience': 3,
    'learning_rate': 2e-5}

model = ClassificationModel('bert', './multi_cased_L-12_H-768_A-12/bert_model.ckpt.data-00000-of-00001' , args=train_args, use_cuda=True) 

Downloaded the mBert from : https://github.com/google-research/bert/blob/master/multilingual.md
