### ISSUE TITLE
Modifying fine-tuned model

### ISSUE THREAD

**Issue by jacobmiller29** [ThilinaRajapakse/simpletransformers#590]
In the absence of the ability to use the sliding window for multilabel classification, I've first fine-tuned a model on binary labels. I'd then like to modify this model to continue fine-tuning on multiclass labels, however, this throws a torch shape error. Is there any simple way to resolve this?

**Comment by ThilinaRajapakse** [comment]
I don't think there's an easy way to resolve this. The shape of the output layer of a binary model is different from the shape of the output layer of a multiclass model. Because of this, you can't directly load a saved model from one into the other.

If you want to do it, I think you will have to load the weights manually.

An alternative solution to the sliding window for multilabel classification might be to manually split the longer texts into shorter chunks and gather all the predicted labels from each chunk to create the predictions for the original text.
