### ISSUE TITLE
Micro and macro scores for mutli-label classification

### ISSUE THREAD

**Issue by woiza** [ThilinaRajapakse/simpletransformers#595]
How can I calculate micro and macro scores? I tried the following:

`
model.train_model(train_df, eval_df=validate_df,mcc=sklearn.metrics.matthews_corrcoef,rocmacro=sklearn.metrics.roc_auc_score(average='macro'),rocmicro=sklearn.metrics.roc_auc_score(average='micro'),f1macro=sklearn.metrics.f1_score(average='macro'),f1micro=sklearn.metrics.f1_score(average='micro'))`

and get this error:

`TypeError: roc_auc_score() missing 2 required positional arguments: 'y_true' and 'y_score'
`

I also tried it with mcc alone:
`model.train_model(train_df, eval_df=validate_df,mcc=sklearn.metrics.matthews_corrcoef)`

and got this error:
`ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets`

The labels are generated/encoded as follows:
`from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
mlb_result = mlb.fit_transform([str(df1.loc[i,'category']).split('\n') for i in range(len(df1))])
df_label = pd.concat([df1['text'],pd.DataFrame(mlb_result,columns=list(mlb.classes_))],axis=1)`

**Comment by AbinayaM02** [comment]
@woiza : Hi. Please find the explanations of the erros you're facing.

TypeError: roc_auc_score() missing 2 required positional arguments: 'y_true' and 'y_score' - This error is occuring because the roc_auc_score() takes in true labels and the model predicted labels as parameters and it's not being passed in your fucntion call.

ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets - This error is because sklearn.metrics.matthews_corrcoef supports only binary and mutlicalss classification but you're using it for a multilabel problem.

**Comment by ThilinaRajapakse** [comment]
Essentially, the metric functions you pass in should accept two arguments, the true labels and the predicted labels. You can pass in the sklearn functions directly when doing something simple like binary classification but for cases like this one, you will have to write a small wrapper function that accepts the two arguments and then internally calls the sklearn function.
