### ISSUE TITLE
Multi class classification error

### ISSUE THREAD

**Issue by samarthsarin** [ThilinaRajapakse/simpletransformers#6]
When I am trying to run the sentiment analysis on multi class classification problem I am getting the  following error.

RuntimeError                              Traceback (most recent call last)
<ipython-input-13-ed5e9ba16145> in <module>()
      1 model = TransformerModel('bert', 'bert-base-cased',args={'fp16':False})
----> 2 model.train_model(train_df)

6 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in convert(t)
    428 
    429         def convert(t):
--> 430             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    431 
    432         return self._apply(convert)

RuntimeError: CUDA error: device-side assert triggered

**Comment by ThilinaRajapakse** [comment]
`bert-base-cased` doesn't support multiclass classification. [This article](https://medium.com/huggingface/multi-label-text-classification-using-bert-the-mighty-transformer-69714fa3fb3d) might be helpful in adapting a sequence classification model for multiple labels.

**Comment by samarthsarin** [comment]
Ok. So how do you recommend to use Multiclass classification using Simple Transformers?

**Comment by ThilinaRajapakse** [comment]
Create a `BertForMultiLabelSequenceClassification` class like the one in the tutorial I linked. Create an object of `BertForMultiLabelSequenceClassification` and load it with the pretrained weights. Use this object as the `model` attribute for the TransformerModel. But this is not supported out of the box. You'll have to change the init method of TransformerModel to use the `BertForMultiLabelSequenceClassification` object rather than a default method.

**Comment by samarthsarin** [comment]
Ok thank you. Will try that.

**Comment by ThilinaRajapakse** [comment]
#10
