### ISSUE TITLE
Evaluate several times for each epoch

### ISSUE THREAD

**Issue by manueltonneau** [ThilinaRajapakse/simpletransformers#620]
Hi again and thanks for the great repo :) 

I am currently looking into evaluating my classification model several times per epoch. I saw that the `evaluate_during_training_steps` allows me to do this. Yet, with varying dataset sizes, the number of steps to complete an epoch varies. 

Is there a way that we could define a parameter of value A (that we could name `evaluate_nb_evaluations_per_epoch`) and that would automatically retrieve the number of steps N to complete an epoch and would allow to evaluate the model at every N/A steps? Or does that already exist?

Thanks a lot in advance.

**Comment by ThilinaRajapakse** [comment]
The evaluation will run at the end of every epoch by default. If you only want the evaluations to run at the end of epochs, you can set `evaluate_during_training_steps` to `-1`.

**Comment by manueltonneau** [comment]
>If you only want the evaluations to run at the end of epochs, you can set evaluate_during_training_steps to -1.

I'm not sure I understand. You mean if I want the evaluation to be run at the end of each epoch?

My goal here is to do several evaluations for each epoch (partly based on the first takeaway of [this article](https://towardsdatascience.com/how-to-make-the-most-out-of-bert-finetuning-d7c9f2ca806c)). Is there a way to do this with the current package? If not, could we implement it?

**Comment by ThilinaRajapakse** [comment]
If `evaluate_during_training` is `True`, then the evaluation will be run at the end of each epoch. **In addition** to that, you can also configure the evaluation to run every _n_ steps (_n_ is controlled by `evaluate_during_training_steps`). The end of epoch evaluation is executed regardless.

Looks like I didn't read your original issue comment properly, sorry. There is no value A that would automatically calculate the number of steps. The available configuration option is to set the number of steps between evaluations rather than the number of evaluations per epoch. But, since the calculation is trivial, I don't think we should add more parameters (having both would cause a conflict if they are set incorrectly as well).

For example, you could do something like this.

```python
model_args = ClassificationArgs()
model_args.evaluate_during_training_steps = len(train_data) // (batch_size * N)   # N is the number of evaluations you want per epoch
```

**Comment by manueltonneau** [comment]
That solves my issue, thanks a lot :)

**Comment by Jefffish09** [comment]
> The evaluation will run at the end of every epoch by default. If you only want the evaluations to run at the end of epochs, you can set `evaluate_during_training_steps` to `-1`.

@ThilinaRajapakse  I have set `evaluate_during_training_steps` to `-1`, but it still made several evaluation in each epoch.
