### ISSUE TITLE
Feature: add non-textual hot-encoded inputs for classification?

### ISSUE THREAD

**Issue by estaub** [ThilinaRajapakse/simpletransformers#672]
Here's an example.  Consider the "toxic comment" example used in [the multi-label classification tutorial](https://towardsdatascience.com/multi-label-classification-using-bert-roberta-xlnet-xlm-and-distilbert-with-simple-transformers-b3e0cda12ce5).  If the comments were labelled by multiple different websites with slightly different opinions on e.g. what is obscene, one might want to tag the inputs with the website it came from.  Then the same model could be used by multiple sites to tag their comments, each according to their own slightly different standards.

In my case, I am working on labelling of US state-level legislation, and in a few areas different states use different terms to refer to the same thing - sometimes muddying the model by conflicting with other usage in other states.  

While my examples both would be supported by one-hot encoding of the extra inputs, **_maybe_** it would make sense to not prohibit multi-hot encoding, for other usages.  I'm no expert!

An alternative, of course, is to tack unique tokens onto the input representing the non-textual input.  If there's a way to, say, create unique tokens for this purpose, or otherwise do it cleanly, I'm all ears.

**Comment by ThilinaRajapakse** [comment]
I think the simplest solution would be to simply prepend (or append) the other input (the state names in your case) to the actual text.

You can add new tokens to the model's vocabulary, but, as far as I am aware, this brings dubious benefits. It's usually sufficient to simply go with the text you have and let the model figure it out. I.e. rather than manually adding a unique token for "New York", you would just prepend all New York related legislation with "New York - ".

I don't think it's possible to add a feature where you could use non-text features alongside (but as a separate input) the text input to the Transformer model itself.

**Comment by estaub** [comment]
Ok, thanks much for the guidance!
