### ISSUE TITLE
W&B data tranmission

### ISSUE THREAD

**Issue by sgummidipundi** [ThilinaRajapakse/simpletransformers#725]
Not so much a problem, but more of a question. I get the following warning message:

wandb: WARNING W&B installed but not logged in. Run wandb login or set the WANDB_API_KEY env variable.

I wanted to make sure that although I'm not logged or set any project, that no data is actually transmitted to W&B. If I did specify an API key, would the only thing that are sent is hyperparameters and weights?

**Comment by ThilinaRajapakse** [comment]
No data will be transmitted unless you are logged in and actually using it (setting a `wandb_project`). The warning is given because the library itself is installed.

It would send the hyperparameters, evaluation scores, and resource utilization info  (GPU usage, CPU usage etc.).

You can check what's being sent by searching for  `wandb.log()` statements across the project.
