### ISSUE TITLE
OSError: Can't download weights for...

### ISSUE THREAD

**Issue by Mokers1234** [ThilinaRajapakse/simpletransformers#810]
from simpletransformers.classification import ClassificationModel
test = ClassificationModel('bert','bert-base-cased')

When running the above, I get the following traceback:

```
Traceback (most recent call last):
  File "c:/Users/Mark/Documents/NLP_comments2/test_download.py", line 2, in <module>
    test = ClassificationModel("bert","bert-base-cased",force_download=True)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36\lib\site-packages\simpletransformers\classification\classification_model.py", line 223, in __init__
    self.model = model_class.from_pretrained(model_name, config=self.config, **kwargs)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modeling_utils.py", line 936, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 'bert-base-cased'. Make sure that:

- 'bert-base-cased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-cased' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.
```

I'm almost certain this is because of my ISP blocking it, despite turning off all firewalls.

I've found a workaround to obtain the config.json and pytorch_model.bin files from the huggingface AWS server, to try to load it via simpletransformers locally eg. 

test = ClassificationModel('bert','./bert-base-cased') #folder containing the .bin and .json files

However it's still missing vocab.txt amongst other files that simpletransformers needs

Is there a way to obtain these, so that I can continue to use simpletransformers?

Thanks!

**Comment by ThilinaRajapakse** [comment]
The `vocab.txt` file is needed to load the tokenizer. So, you'll need to download those too. Everything needed is available in the HF server although I don't know specifically where. `vocab.txt` should be somewhere related to `BertTokenizer`.

If the ISP issue is because you need to set a proxy, you can also do that by passing the proxy details as a keyword argument to `ClassificationModel`. More info [here](https://huggingface.co/transformers/master/main_classes/configuration.html?highlight=proxy).

You could also use Colab to get the files, I guess.

E.g.:

```python
model = ClassificationModel("bert", "bert-base-cased")
model.save_model(model=model.model)
```
This will save the model to `outputs` and you can download it from there.

I've attached the files (other than the `pytorch_model.bin` file) for `bert-base-cased` here as well.

[outputs.zip](https://github.com/ThilinaRajapakse/simpletransformers/files/5518887/outputs.zip)

**Comment by Mokers1234** [comment]
Thank you very much for addressing the problem. It was indeed a problem with my ISP, Virgin Media. It wasn't a firewall issue, but their "Virus safe" setting which was prohibiting the download. Disabling it in the members area solved the issue.

**Comment by Mokers1234** [comment]
I have a new problem which I have described in a closed thread on the same topic here, if you could please take a look Thilina:
https://github.com/ThilinaRajapakse/simpletransformers/issues/225
