### ISSUE TITLE
For  multilabel classification before compute_metrics should  do onehot

### ISSUE THREAD

**Issue by MrRace** [ThilinaRajapakse/simpletransformers#827]
**Describe the bug**
For text multilabel classification, in the line :
https://github.com/ThilinaRajapakse/simpletransformers/blob/0cf4ffcdf83ee339f657c10789542e892d3ba2b4/simpletransformers/classification/classification_model.py#L997

it seems should be that:
```
            if not multi_label:
                preds = np.argmax(preds, axis=1)
            else:
                preds = (preds > 0.5).astype(int)
```
otherwise the  compute_metrics would fail!

**Comment by ThilinaRajapakse** [comment]
But it's working fine without this, right?

**Comment by abhinavg97** [comment]
Yes, I think the else is important as if we do not put ```preds = (preds > threshold).astype(int)``` then the model would not threshold and the mismatched variable would have the wrong value. 

For example for threshold = 0.5 and with 3 labels,

labels = [0,1,0]
preds = [0.01, 0.9, 0.2]

would be predicted as mismatched because of this line
```
        mismatched = labels != preds
``` 
in https://github.com/ThilinaRajapakse/simpletransformers/blob/0cf4ffcdf83ee339f657c10789542e892d3ba2b4/simpletransformers/classification/classification_model.py#L1171

But actually after thresholding this example is indeed predicted correctly.

**Comment by MrRace** [comment]
> But it's working fine without this, right?

Not, it  would break down in the  https://github.com/ThilinaRajapakse/simpletransformers/blob/0cf4ffcdf83ee339f657c10789542e892d3ba2b4/simpletransformers/classification/classification_model.py#L1168
when use metric like micro_f1
