### ISSUE TITLE
Training custom models

### ISSUE THREAD

**Issue by Chokerino** [ThilinaRajapakse/simpletransformers#836]
Hello,

I wanted to train bert/bert like models on protein sequences. In this case, using this library and training my sequence would be incorrect because the bert model which is being used are the ones trained on English language? if this is the case is there any example I can follow to train my own model based on my own vocabulary. Also, what is the recommended amount of data points one needs to have to train a bert-like model.

**Comment by ThilinaRajapakse** [comment]
I'm not familiar with using language models on protein sequences, but I know that this is an active research area. I don't think the BERT models pre-trained on English will work well for this, but there may be pre-trained models available which were trained for protein sequences.

You can train your own models using the `LanguageModelingModel` (see docs for examples). Pre-training a model for a language usually needs GBs of text and a lot of computing resources. Again, I'm not sure how that'll translate to your task.

**Comment by Chokerino** [comment]
Also, considering the fact that protein sequences will be very large i.e around 10000 letters compared to an English sentence which is comparatively very small, will architectures like BERT perform poorly cause they are not meant for longer sentences?

**Comment by ThilinaRajapakse** [comment]
That would depend on the tokenization algorithm used. GPU memory required to train a BERT-like model grows quadratically (for the self-attention layers) with the sequence length. If your sequences have significantly more tokens, then BERT will not be suitable (BERT has a maximum sequence length of 512).

You can look into models like the Reformer which tackle this problem. In fact, there was one model that deals with the sequence length issue precisely because it was designed to work on protein sequences (or some sort of biology sequence thingy anyway!). I can't quite recall which one it was though.

**Comment by Chokerino** [comment]
@ThilinaRajapakse I tried to train electra but I think i keep running out of memory on the university server. How much disk space does training a model take? Also, since your library does not support reformers yet, is there any other easy way to train them?

**Comment by ThilinaRajapakse** [comment]
Disk space is not really a concern for training a model unless you save a large number of checkpoints. A single "base" model is usually around 300-400 MB depending on the model type.

The memory that you are running out of is likely GPU (CUDA) memory.

It's probably possible to train reformers with Huggingface Transformers, but I can't say for sure since I haven't looked into it yet.

**Comment by Chokerino** [comment]
Hey i was able to sort that out and I trained a language model on about 50k lines to text. Although when i try to fine tune it for classification on about 500 lines of text, i get some kind of memory error. ( Page size is too small ). It works fine when i train it on a smaller dataset compared to the 50k. Is there any way to fix this while being on the same system @ThilinaRajapakse.
