### ISSUE TITLE
How to provide class weights in NER? 

### ISSUE THREAD

**Issue by overlookcurl** [ThilinaRajapakse/simpletransformers#872]
I am using the package for an NER task. Is it possible provide class weights in NER. If so will you be able to provide an example? I am sorry if it is already available. I tried to find it. But could not. 

Thank you for the awesome package.

**Comment by ThilinaRajapakse** [comment]
Class weights aren't available for NER atm. I've been dragging my heels on this because it requires subclassing the Huggingface model classes (and that makes things more prone to break during updates). But I guess the advantages do outweigh the concerns in this case, so I'll look into adding this in a future update.
